# Generated by Django 2.2.3 on 2019-08-12 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tienda_almacen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente2',
            fields=[
                ('cedula', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=20)),
                ('lastname', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(default='', max_length=30)),
                ('phone', models.CharField(default='', max_length=20)),
                ('seller', models.BooleanField(default=False)),
                ('contra', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_compra', models.CharField(max_length=30)),
                ('oferta', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('precioTotal', models.BigIntegerField()),
                ('nombre_cliente', models.CharField(max_length=20)),
                ('comprax', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booleano', models.BooleanField(default=False)),
                ('ofertaz', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('numero_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('cliente', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tienda_venta.Cliente2')),
            ],
        ),
        migrations.CreateModel(
            name='PseudoJoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedidos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda_venta.Pedido')),
                ('productos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda_almacen.Producto')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda_venta.Cliente2')),
            ],
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id_envio', models.IntegerField(primary_key=True, serialize=False)),
                ('dir_destino', models.CharField(max_length=30)),
                ('precio_envio', models.IntegerField()),
                ('date', models.DateField()),
                ('hora', models.DateTimeField()),
                ('factura', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tienda_venta.Factura')),
            ],
        ),
    ]
