# Generated by Django 2.2.3 on 2019-07-07 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tienda_suscripcion', '0001_initial'),
        ('tienda_almacen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('numero_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('cliente', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tienda_venta.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='tienda_venta.Pedido')),
                ('productoy', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tienda_almacen.Producto')),
                ('tienday', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tienda_suscripcion.Tienda')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('precioTotal', models.BigIntegerField()),
                ('nombre_cliente', models.CharField(max_length=20)),
                ('pedido', models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='tienda_venta.Pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id_envio', models.IntegerField(primary_key=True, serialize=False)),
                ('dir_destino', models.CharField(max_length=30)),
                ('precio_envio', models.IntegerField()),
                ('date', models.DateField()),
                ('hora', models.DateTimeField()),
                ('factura', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tienda_venta.Factura')),
            ],
        ),
    ]
