# Generated by Django 2.2.3 on 2019-09-01 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_venta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('nombre_tarjeta', models.CharField(max_length=20)),
                ('numero_tarjeta', models.CharField(max_length=40, primary_key=True, serialize=False)),
            ],
        ),
    ]
