# Generated by Django 2.2.3 on 2019-07-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_venta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='creditcard',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='lastname',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='passw',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='cliente',
            name='seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(default='', max_length=20),
        ),
    ]
