# Generated by Django 2.2.3 on 2019-07-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_venta', '0002_auto_20190715_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
