# Generated by Django 2.2.3 on 2019-09-17 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_venta', '0003_join2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura2',
            fields=[
                ('numero_factura', models.AutoField(primary_key=True, serialize=False)),
                ('saldoTotal', models.DecimalField(blank=True, decimal_places=0, default=None, max_digits=19, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tienda', models.CharField(max_length=40)),
            ],
        ),
    ]
