# Generated by Django 2.2.3 on 2019-09-17 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_venta', '0005_auto_20190917_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join2',
            name='facturax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda_venta.Factura2'),
        ),
    ]
