# Generated by Django 2.2.3 on 2019-09-17 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_venta', '0006_auto_20190917_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join2',
            name='facturax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='join2', to='tienda_venta.Factura2'),
        ),
    ]
