# Generated by Django 2.2.3 on 2019-07-29 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_almacen', '0007_auto_20190725_1441'),
        ('tienda_venta', '0009_auto_20190729_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteOferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientez', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tienda_venta.Cliente2')),
                ('pedidoz', models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='tienda_venta.Pedido')),
                ('productoz', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tienda_almacen.Producto')),
            ],
        ),
    ]
