# Generated by Django 2.2.3 on 2019-07-30 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_venta', '0013_oferta_booleano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='numero_oferta',
            field=models.CharField(default='', max_length=20, primary_key=True, serialize=False),
        ),
    ]
