# Generated by Django 2.2.3 on 2019-07-31 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_venta', '0014_auto_20190730_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clienteoferta',
            name='id',
        ),
        migrations.RemoveField(
            model_name='clienteoferta',
            name='ofertaz',
        ),
        migrations.RemoveField(
            model_name='oferta',
            name='numero_oferta',
        ),
        migrations.AddField(
            model_name='clienteoferta',
            name='numero_compra',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='compra',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oferta',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oferta',
            name='ofertaz',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='tienda_venta.ClienteOferta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compra',
            name='numero_compra',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='compra',
            name='oferta',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='factura',
            name='comprax',
            field=models.CharField(max_length=20),
        ),
    ]
