# Generated by Django 2.2.3 on 2019-07-31 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_venta', '0015_auto_20190731_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienteoferta',
            name='numero_compra',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
