# Generated by Django 2.2.3 on 2019-07-31 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_venta', '0016_auto_20190731_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='ofertaz',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='ClienteOferta',
        ),
    ]
