# Generated by Django 2.2.3 on 2019-07-31 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_almacen', '0008_auto_20190729_2231'),
        ('tienda_venta', '0017_auto_20190731_0451'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteOferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productoy', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tienda_almacen.Producto')),
                ('tienday', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tienda_venta.Cliente2')),
            ],
        ),
    ]
