# Generated by Django 2.2.3 on 2019-07-31 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_venta', '0018_clienteoferta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clienteoferta',
            name='id',
        ),
        migrations.AddField(
            model_name='clienteoferta',
            name='ofertx',
            field=models.AutoField(default=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='ofertaz',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tienda_venta.ClienteOferta'),
        ),
    ]
