# Generated by Django 2.2.3 on 2019-07-31 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_almacen', '0008_auto_20190729_2231'),
        ('tienda_venta', '0019_auto_20190731_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfertaProducto',
            fields=[
                ('ofertaz', models.AutoField(primary_key=True, serialize=False)),
                ('productoz', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tienda_almacen.Producto')),
                ('tiendaz', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tienda_venta.Cliente2')),
            ],
        ),
    ]
