# Generated by Django 2.2.3 on 2019-08-01 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_venta', '0020_ofertaproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='ofertaz',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tienda_venta.OfertaProducto'),
        ),
        migrations.DeleteModel(
            name='ClienteOferta',
        ),
    ]
