# Generated by Django 2.2.3 on 2019-08-12 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('cantidad_producto', models.IntegerField()),
                ('precio_unidad', models.DecimalField(blank=True, decimal_places=10, default=None, max_digits=19, null=True)),
                ('descripcion', models.CharField(default='', max_length=200)),
                ('images', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
