# Generated by Django 2.2.3 on 2019-08-24 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_almacen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda_almacen.Categoria'),
        ),
    ]
