# Generated by Django 2.2.3 on 2019-08-08 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_almacen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='producto',
            name='images',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='producto',
            name='photo',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
