# Generated by Django 2.2.3 on 2019-07-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_almacen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='photo',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
