# Generated by Django 2.2.3 on 2019-08-08 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_almacen', '0003_auto_20190808_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='id_producto',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
