# Generated by Django 2.2.3 on 2019-07-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_almacen', '0003_producto_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='images',
            field=models.CharField(default='', max_length=500),
        ),
    ]
