# Generated by Django 2.2.3 on 2019-07-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_almacen', '0004_producto_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='images',
            field=models.CharField(default='../../static/', max_length=500),
        ),
    ]
