# Generated by Django 2.2.3 on 2019-09-13 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_almacen', '0006_auto_20190901_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio_unidad',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
