# Generated by Django 2.2.3 on 2019-09-13 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_almacen', '0008_auto_20190913_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio_unidad',
            field=models.DecimalField(blank=True, decimal_places=0, default=None, max_digits=19, null=True),
        ),
    ]
